In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import confusion_matrix, classification_report, auc, roc_curve

In [15]:
train=pd.read_csv("C:\\Users\\prasa\\Downloads\\SalaryData_Train.csv")
train.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [16]:
# Converting categorical data into numerical data
df=train.iloc[:,:13]
x_train=pd.get_dummies(df)
x_train.head()

age  educationno  capitalgain  capitalloss  hoursperweek  \
0   39           13         2174            0            40   
1   50           13            0            0            13   
2   38            9            0            0            40   
3   53            7            0            0            40   
4   28           13            0            0            40   

   workclass_ Federal-gov  workclass_ Local-gov  workclass_ Private  \
0                       0                     0                   0   
1                       0                     0                   0   
2                       0                     0                   1   
3                       0                     0                   1   
4                       0                     0                   1   

   workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  ...  \
0                        0                            0  ...   
1                        0                            1  ...   
2                        0                            0  ...   
3                        0                            0  ...   
4                        0                            0  ...   

   native_ Portugal  native_ Puerto-Rico  native_ Scotland  native_ South  \
0                 0                    0                 0              0   
1                 0                    0                 0              0   
2                 0                    0                 0              0   
3                 0                    0                 0              0   
4                 0                    0                 0              0   

   native_ Taiwan  native_ Thailand  native_ Trinadad&Tobago  \
0               0                 0                        0   
1               0                 0                        0   
2               0                 0                        0   
3               0                 0                        0   
4               0                 0                        0   

   native_ United-States  native_ Vietnam  native_ Yugoslavia  
0                      1                0                   0  
1                      1                0                   0  
2                      1                0                   0  
3                      1                0                   0  
4                      0                0                   0  

[5 rows x 102 columns]

In [17]:
y_train=train.iloc[:,-1]
y_train

0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
          ...  
30156     <=50K
30157      >50K
30158     <=50K
30159     <=50K
30160      >50K
Name: Salary, Length: 30161, dtype: object

In [18]:
test=pd.read_csv("C:\\Users\\prasa\\Downloads\\SalaryData_Test.csv")

In [24]:
x_test=test.iloc[:,:13]
x_test.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  
0            0            40   United-States  
1            0            50   United-States  
2            0            40   United-States  
3            0            40   United-States  
4            0            30   United-States

In [25]:
x_test=pd.get_dummies(x_test)
x_test

age  educationno  capitalgain  capitalloss  hoursperweek  \
0       25            7            0            0            40   
1       38            9            0            0            50   
2       28           12            0            0            40   
3       44           10         7688            0            40   
4       34            6            0            0            30   
...    ...          ...          ...          ...           ...   
15055   33           13            0            0            40   
15056   39           13            0            0            36   
15057   38           13            0            0            50   
15058   44           13         5455            0            40   
15059   35           13            0            0            60   

       workclass_ Federal-gov  workclass_ Local-gov  workclass_ Private  \
0                           0                     0                   1   
1                           0                     0                   1   
2                           0                     1                   0   
3                           0                     0                   1   
4                           0                     0                   1   
...                       ...                   ...                 ...   
15055                       0                     0                   1   
15056                       0                     0                   1   
15057                       0                     0                   1   
15058                       0                     0                   1   
15059                       0                     0                   0   

       workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  ...  \
0                            0                            0  ...   
1                            0                            0  ...   
2                            0                            0  ...   
3                            0                            0  ...   
4                            0                            0  ...   
...                        ...                          ...  ...   
15055                        0                            0  ...   
15056                        0                            0  ...   
15057                        0                            0  ...   
15058                        0                            0  ...   
15059                        1                            0  ...   

       native_ Portugal  native_ Puerto-Rico  native_ Scotland  native_ South  \
0                     0                    0                 0              0   
1                     0                    0                 0              0   
2                     0                    0                 0              0   
3                     0                    0                 0              0   
4                     0                    0                 0              0   
...                 ...                  ...               ...            ...   
15055                 0                    0                 0              0   
15056                 0                    0                 0              0   
15057                 0                    0                 0              0   
15058                 0                    0                 0              0   
15059                 0                    0                 0              0   

       native_ Taiwan  native_ Thailand  native_ Trinadad&Tobago  \
0                   0                 0                        0   
1                   0                 0                        0   
2                   0                 0                        0   
3                   0                 0                        0   
4                   0                 0                        0   
...               ...               ...                      ...   
15055               0              

In [29]:
y_test=test.iloc[:,-1]
y_test

0         <=50K
1         <=50K
2          >50K
3          >50K
4         <=50K
          ...  
15055     <=50K
15056     <=50K
15057     <=50K
15058     <=50K
15059      >50K
Name: Salary, Length: 15060, dtype: object

## Without Using Scaling

In [42]:
gnb= GaussianNB()

In [43]:
gnb.fit(x_train,y_train)

GaussianNB()

In [44]:
y_pred = gnb.predict(x_test)

In [45]:
accuracy = np.round(accuracy_score(y_test, y_pred)*100, 2)
print(f"Accuracy of unscaled model is {accuracy} %")

Accuracy of unscaled model is 80.29 %


In [48]:
conf_mat= confusion_matrix(y_test, y_pred)
print(conf_mat)

[[9073 2287]
 [ 681 3019]]


## Using Min-Max Scalar

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
scaled= MinMaxScaler()

In [32]:
x_train_mm= scaled.fit_transform(x_train)
x_test_mm= scaled.transform(x_test)

In [33]:
x_train_mm

array([[0.30136986, 0.8       , 0.02174022, ..., 1.        , 0.        ,
        0.        ],
       [0.45205479, 0.8       , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.28767123, 0.53333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.56164384, 0.53333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.06849315, 0.53333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.47945205, 0.53333333, 0.1502415 , ..., 1.        , 0.        ,
        0.        ]])

In [34]:
x_test_mm

array([[0.10958904, 0.4       , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.28767123, 0.53333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.15068493, 0.73333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.28767123, 0.8       , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.36986301, 0.8       , 0.05455055, ..., 1.        , 0.        ,
        0.        ],
       [0.24657534, 0.8       , 0.        , ..., 1.        , 0.        ,
        0.        ]])

In [35]:
gnb_minmax= GaussianNB()

In [36]:
gnb_minmax.fit(x_train_mm, y_train)

GaussianNB()

In [38]:
y_pred_minmax = gnb_minmax.predict(x_test_mm)

In [40]:
from sklearn.metrics import accuracy_score
accuracy_minmax = np.round(accuracy_score(y_test, y_pred_minmax)*100,2)
print(f"Accuracy of MinMax scaled model is {accuracy_minmax} % ")

Accuracy of MinMax scaled model is 57.78 % 


In [49]:
conf_mat_minmax = confusion_matrix(y_test, y_pred_minmax)
print(conf_mat_minmax)

[[5265 6095]
 [ 264 3436]]


## Using Robust Scalar

In [50]:
from sklearn.preprocessing import RobustScaler

In [51]:
robsc= RobustScaler()

In [52]:
x_train_rob = robsc.fit_transform(x_train)
x_test_rob = robsc.transform(x_test)

In [53]:
gnb_rob = GaussianNB()

In [54]:
gnb_rob.fit(x_train_rob, y_train)
y_pred_rob = gnb_rob.predict(x_test_rob)

In [55]:
accuracy_rob= np.round(accuracy_score(y_test, y_pred_rob)*100,2)
print(f"Accuracy of Robust scaled model is {accuracy_rob} % ")

Accuracy of Robust scaled model is 80.1 % 


In [56]:
conf_mat_rob = confusion_matrix(y_test, y_pred_rob)
print(conf_mat_rob)

[[9035 2325]
 [ 672 3028]]
